[files]
extend-exclude = [
    "fmt",
    "minhook",
    "pybind11",
    "LICENSE",
    ".typos.toml",

    "AltUseVendors",
    "ApplesBorderlandsCheats",
    "EquipLocker",
    "ItemLevelUncapper",
    "Onezerker",
    "PythonPartNotifier",
    "SanitySaver",
    "TextModLoader",
    "UserFeedback",

    "command_extensions/file_parser_tests/*.test_in",
    "vendor_edit/zdict_experiments",
    "vendor_edit/zdict",
]

[default]
extend-ignore-re = [
    # Ignore markdown links to github commits/trees
    "\\[[0-9a-fA-F]+?\\]\\(https://github.com/.+?/.+?/(commit|tree)/.+?\\)",
    # Ignore this specific hook string, which gearbox typo'd
    "\"WillowGame\\.WillowPlayerController:CanAcessOakUpsell\"",
    # Ignore the `EInventorySortType` enum prefix
    "IST_\\w+",
    # Ignore the `Ake` Ak Event prefix
    "Ake_\\w+",
    "AKE_\\w+",
]

[default.extend-identifiers]
llibgcc_s_seh = "llibgcc_s_seh"

[default.extend-words]
UE = "UE"
